name: Deploy Frontend

on:
  push:
    branches:
      - master   # rama para producción

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js
        run: npm run build

      - name: Prepare artifact
        run: |
          npm prune --omit=dev
          mkdir -p release
          cp -R .next package.json ecosystem.config.js node_modules public release/
          tar -czf release.tar.gz -C release .

      - name: Copy to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "release.tar.gz"
          target: "/var/www/frontend"

      - name: Deploy on server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/frontend
            rm -rf .next node_modules public package.json
            tar -xzf release.tar.gz
            rm release.tar.gz
            pm2 delete frontend || true
            pm2 start ecosystem.config.js
